'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
import {money} from '@/lib/rules';
import {useAuth} from '@/context/AuthContext';
import {productSlug} from '@/lib/slugs';
const labels:Record<string,string>={available:'A la venta',reserved:'Reservado',sold:'Vendido',expired:'Finalizado',withdrawn:'Retirado',pending_payment:'Pendiente de pago',paid:'Pagado',shipped:'Enviado',completed:'Completado',cancelled:'Cancelado',refunded:'Reembolsado',disputed:'En revisión'};
export default function Activity(){const {user,loading}=useAuth();const [data,setData]=useState<any>(null);const [tab,setTab]=useState('purchases');const [error,setError]=useState('');const [withdraw,setWithdraw]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{if(user)api('activity').then(setData).catch(e=>setError(e.message))},[user]);async function remove(){setBusy(true);try{await api('withdraw/'+withdraw,{});setData(await api('activity'));setWithdraw('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
if(loading)return <p>Cargando…</p>;if(!user)return <div className="empty-state"><h1>Tus tratos, en un solo sitio.</h1><p>Entra para seguir tus compras, ventas y pujas.</p><Link href="/login" className="button primary">Entrar</Link></div>;const rows=!data?[]:tab==='listings'?data.listings:tab==='bids'?data.bids:data.orders.filter((o:any)=>tab==='purchases'?o.buyer_id===user.id:o.seller_id===user.id);
return <><div className="catalog-head"><div><span className="eyebrow">TU ESPACIO</span><h1>Mi actividad</h1></div><Link className="button primary" href="/publish-ad">＋ Vender un artículo</Link></div><div className="mode-tabs activity-tabs">{[['purchases','Compras'],['sales','Ventas'],['bids','Mis pujas'],['listings','Mis anuncios']].map(([v,t])=><button key={v} className={tab===v?'active':''} onClick={()=>setTab(v)}>{t}</button>)}</div>{error&&<p className="error-message">{error}</p>}{!data&&!error?<p>Cargando actividad…</p>:!rows.length?<div className="empty-state"><h2>Todavía no hay actividad aquí</h2><p>Los artículos y pedidos aparecerán aquí cuando participes.</p><Link href="/" className="button">Explorar artículos</Link></div>:<div className="activity-list">{rows.map((r:any)=>{const l=r.listing||r;const slug=productSlug(r.listing_id||r.id,l.title);return <article key={r.id} className="activity-row"><img src={l.images[0]} alt={l.title}/><div><h3><Link href={tab==='listings'||tab==='bids'?'/articulos/'+slug:'/orders/'+r.id}>{l.title}</Link></h3><p className="muted">{labels[r.status||l.status]||r.status} · {new Date(r.created_at).toLocaleDateString('es-ES')}</p></div><strong>{money(r.amount_cents||r.price_cents)}</strong>{tab==='listings'?r.status==='available'&&!r.bid_count?<button className="button" onClick={()=>setWithdraw(r.id)}>Retirar</button>:null:tab!=='bids'?<Link className="button" href={'/orders/'+r.id}>Ver pedido →</Link>:<Link className="button" href={'/articulos/'+slug}>Ver subasta →</Link>}</article>})}</div>}{withdraw&&<div className="confirmation"><h2>¿Retirar este anuncio?</h2><p>Se conservará en tu historial y dejará de estar a la venta.</p><button className="button primary" disabled={busy} onClick={remove}>Retirar anuncio</button><button className="button" onClick={()=>setWithdraw('')}>Cancelar</button></div>}</>}
