import {NextResponse} from 'next/server';
import {createClient} from '@/utils/supabase/server';
import {admin,card,publicFields,rpc} from '@/models/marketplace';
import {categories,conditions,cents,text,noContact,uuid,canMessage} from '@/lib/rules';
import {stripe,origin} from '@/lib/payments';
import {extractIdFromSlug,productSlug} from '@/lib/slugs';
export async function currentUser(){const client=await createClient();const {data:{user}}=await client.auth.getUser();return user}
const simulated=()=>process.env.LAPELA_PAYMENTS_MODE==='simulated';
const environment=()=>simulated()?'sandbox':'live';
const ok=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function result(query:any){const {data,error}=await query;if(error)throw Error('No se ha podido completar la operación. Inténtalo de nuevo.');return data}
async function maintain(){await rpc('lp_close_auctions');const db=admin();const expired=await result(db.from('lp_orders').select('id,stripe_session_id').eq('status','pending_payment').lt('expires_at',new Date().toISOString()).limit(20));for(const o of expired){if(o.stripe_session_id){if(!process.env.STRIPE_SECRET_KEY)continue;const session=await stripe().checkout.sessions.retrieve(o.stripe_session_id);if(session.status==='complete')continue;if(session.status==='open'){try{await stripe().checkout.sessions.expire(session.id)}catch{continue}}}await rpc('lp_release',{p_order:o.id})}}
export async function catalog(request:Request){try{await maintain();const p=new URL(request.url).searchParams;let query=admin().from('lp_listings').select(publicFields,{count:'exact'}).eq('status','available').eq('environment',environment());const q=(p.get('q')||'').slice(0,100).replace(/[%_(),]/g,' ');if(q)query=query.or(`title.ilike.%${q}%,description.ilike.%${q}%`);const category=p.get('category');if(category&&categories.includes(category))query=query.eq('category',category);if(['sale','auction'].includes(p.get('mode')||''))query=query.eq('mode',p.get('mode'));for(const [key,op] of [['minPrice','gte'],['maxPrice','lte']] as const){const v=p.get(key);if(v&&Number.isFinite(Number(v))&&Number(v)>=0)query=query[op]('price_cents',Math.round(Number(v)*100))}if(p.get('location'))query=query.ilike('location','%'+p.get('location')!.replace(/[%_]/g,'').slice(0,80)+'%');const sort=p.get('sort');if(sort==='ending')query=query.eq('mode','auction').order('ends_at');else if(sort?.startsWith('price-'))query=query.order('price_cents',{ascending:sort==='price-asc'});else query=query.order('created_at',{ascending:false});const page=Math.max(1,Math.min(10000,Number.parseInt(p.get('page')||'1')||1));const {data,error,count}=await query.range((page-1)*12,page*12-1);if(error)throw error;return ok({products:data?.map(card)||[],totalCount:count})}catch{return ok({error:'El catálogo no está disponible temporalmente.'},503)}}
export async function handle(request:Request,path:string[]){try{
 const db=admin();const [action,id]=path;const targetId=extractIdFromSlug(id||'');const user=await currentUser();
 if(request.method==='GET'){
  if(action==='listing'&&targetId&&uuid(targetId)){await maintain();const l=await result(db.from('lp_listings').select('*').eq('id',targetId).maybeSingle());if(!l||l.environment!==environment())return ok({error:'Artículo no encontrado'},404);const mine=l.seller_id===user?.id;const {seller_id,highest_bidder,...safe}=l;return ok({...safe,slug:productSlug(l.id,l.title),mine,isHighestBidder:!!user&&highest_bidder===user.id,paymentsReady:simulated()||!!process.env.STRIPE_SECRET_KEY,simulated:simulated()});}
  if(!user)return ok({error:'Inicia sesión para continuar.'},401);
  if(action==='activity'){await maintain();const [listings,orders,bids]=await Promise.all([result(db.from('lp_listings').select('*').eq('seller_id',user.id).order('created_at',{ascending:false})),result(db.from('lp_orders').select('*,listing:lp_listings(title,images,delivery)').or(`buyer_id.eq.${user.id},seller_id.eq.${user.id}`).order('created_at',{ascending:false})),result(db.from('lp_bids').select('*,listing:lp_listings(title,images,price_cents,ends_at,status)').eq('bidder_id',user.id).order('created_at',{ascending:false}))]);return ok({listings,orders,bids,userId:user.id})}
  if(action==='order'&&uuid(id||'')){const o=await result(db.from('lp_orders').select('*,listing:lp_listings(title,images,delivery,location)').eq('id',id).or(`buyer_id.eq.${user.id},seller_id.eq.${user.id}`).maybeSingle());if(!o)return ok({error:'Pedido no encontrado'},404);const allowed=canMessage(o.status,user.id,o.buyer_id,o.seller_id);const messages=allowed?await result(db.from('lp_messages').select('*').eq('order_id',id).order('created_at').limit(500)):[];if(!allowed)o.shipping_address=null;return ok({order:o,messages,userId:user.id,simulated:simulated(),canMessage:allowed})}
 }
 if(request.method!=='POST')return ok({error:'Ruta no encontrada'},404);
 const reqOrigin=request.headers.get('origin');if(reqOrigin&&reqOrigin!==new URL(request.url).origin&&reqOrigin!==process.env.APP_URL)return ok({error:'Origen no permitido'},403);
 if(!user)return ok({error:'Inicia sesión para continuar.'},401);
 if(action==='upload'){
  const form=await request.formData();const f=form.get('file');if(!(f instanceof File)||!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024)return ok({error:'Elige una imagen JPG, PNG o WebP de hasta 5 MB.'},400);
  const bytes=new Uint8Array(await f.arrayBuffer());const valid=(f.type==='image/jpeg'&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255)||(f.type==='image/png'&&bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10')||(f.type==='image/webp'&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP');if(!valid)return ok({error:'El archivo no es una imagen válida.'},400);
  const key=`v2/${user.id}/${crypto.randomUUID()}.${f.type.split('/')[1]}`;const {error}=await db.storage.from('product-images').upload(key,bytes,{contentType:f.type,upsert:false});if(error)throw Error('No se ha podido subir la foto.');return ok({url:db.storage.from('product-images').getPublicUrl(key).data.publicUrl});
 }
 const body=await request.json();
 if(action==='publish'){
  const title=noContact(text(body.title,5,100)),description=noContact(text(body.description,30,4000)),location=noContact(text(body.location,2,80));
  if(!categories.includes(body.category)||!conditions.includes(body.condition)||!['sale','auction'].includes(body.mode)||!['pickup','shipping'].includes(body.delivery))throw Error('Revisa la categoría, el estado y el tipo de venta.');
  if(!Array.isArray(body.images)||body.images.length<1||body.images.length>6||body.images.some((url:unknown)=>typeof url!=='string'||!url.startsWith(process.env.NEXT_PUBLIC_SUPABASE_URL+'/storage/v1/object/public/product-images/v2/'+user.id+'/')))throw Error('Sube entre una y seis fotos del artículo.');
  const end=body.mode==='auction'?new Date(body.ends_at):null;if(end&&(!Number.isFinite(end.getTime())||end.getTime()<Date.now()+3600000||end.getTime()>Date.now()+30*86400000))throw Error('La subasta debe durar entre una hora y treinta días.');
  const price=cents(body.price),buyNow=body.mode==='auction'&&body.buy_now?cents(body.buy_now):null;if(buyNow&&buyNow<=price)throw Error('Comprar ahora debe superar el precio de salida.');
  const shipping=body.delivery==='shipping'?Math.round(Number(body.shipping||0)*100):0;if(!Number.isInteger(shipping)||shipping<0||shipping>10000)throw Error('Revisa los gastos de envío.');
  const recent=await db.from('lp_listings').select('id',{head:true,count:'exact'}).eq('seller_id',user.id).gte('created_at',new Date(Date.now()-3600000).toISOString());if((recent.count||0)>=20)return ok({error:'Has alcanzado el límite de publicaciones por hora.'},429);
  const l=await result(db.from('lp_listings').insert({seller_id:user.id,environment:environment(),title,description,location,category:body.category,condition:body.condition,mode:body.mode,delivery:body.delivery,images:body.images,price_cents:price,buy_now_cents:buyNow,shipping_cents:shipping,ends_at:end?.toISOString()||null}).select('id').single());return ok(l,201);
 }
 if(action==='bid'&&uuid(targetId||'')){const l=await rpc('lp_bid',{p_listing:targetId,p_actor:user.id,p_amount:cents(body.amount)});return ok({price_cents:l.price_cents,bid_count:l.bid_count,ends_at:l.ends_at})}
 if(action==='checkout'&&uuid(targetId||'')){
  if(simulated()){let o;if(body.order){o=await result(db.from('lp_orders').select('*').eq('id',targetId).eq('buyer_id',user.id).eq('status','pending_payment').single())}const l=await result(db.from('lp_listings').select('environment').eq('id',o?o.listing_id:targetId).single());if(l.environment!=='sandbox')throw Error('Solo puedes simular compras de prueba.');if(!o)o=await rpc('lp_reserve',{p_listing:targetId,p_actor:user.id});return ok({url:'/orders/'+o.id});}

  const st=stripe();const base=origin();let o;
  if(body.order){o=await result(db.from('lp_orders').select('*').eq('id',targetId).eq('buyer_id',user.id).eq('status','pending_payment').single())}
  const listing=await result(db.from('lp_listings').select('*').eq('id',o?o.listing_id:targetId).single());
  if(listing.environment!=='live')throw Error('Los artículos de prueba no admiten cobros reales.');
  const account=await result(db.from('lp_accounts').select('stripe_account_id').eq('user_id',listing.seller_id).maybeSingle());if(!account)throw Error('El vendedor todavía no ha activado sus cobros. No se ha realizado ningún cargo.');const connected=await st.accounts.retrieve(account.stripe_account_id);if(!connected.charges_enabled)throw Error('El vendedor debe completar la activación de sus cobros.');
  if(!o)o=await rpc('lp_reserve',{p_listing:targetId,p_actor:user.id});
  if(o.stripe_session_id){const existing=await st.checkout.sessions.retrieve(o.stripe_session_id);if(existing.status==='open'&&existing.url)return ok({url:existing.url});throw Error('El pago ya se ha procesado o ha caducado. Revisa Mis compras.');}
  const session=await st.checkout.sessions.create({mode:'payment',payment_method_types:['card'],client_reference_id:o.id,metadata:{order_id:o.id},customer_email:user.email,expires_at:Math.floor(Date.now()/1000)+30*60,line_items:[{price_data:{currency:'eur',unit_amount:o.amount_cents,product_data:{name:listing.title+(listing.delivery==='shipping'?' · envío incluido':' · recogida en persona')}},quantity:1}],shipping_address_collection:listing.delivery==='shipping'?{allowed_countries:['ES']}:undefined,payment_intent_data:{transfer_data:{destination:account.stripe_account_id},metadata:{order_id:o.id}},success_url:base+'/orders/'+o.id+'?payment=received',cancel_url:base+'/orders/'+o.id},{idempotencyKey:'lapela-order-'+o.id});
  await result(db.from('lp_orders').update({stripe_session_id:session.id,expires_at:new Date((session.expires_at+60)*1000).toISOString()}).eq('id',o.id).eq('status','pending_payment'));return ok({url:session.url});
 }
 if(action==='simulate-payment'&&uuid(id||'')){if(!simulated())return ok({error:'La simulación está desactivada'},403);return ok(await rpc('lp_simulate_payment',{p_order:id,p_actor:user.id}))}
 if(action==='message'&&uuid(id||'')){const content=text(body.content,1,2000);const recent=await db.from('lp_messages').select('id',{count:'exact',head:true}).eq('sender_id',user.id).gte('created_at',new Date(Date.now()-60000).toISOString());if((recent.count||0)>=20)return ok({error:'Espera un momento antes de enviar más mensajes.'},429);return ok(await rpc('lp_send_message',{p_order:id,p_actor:user.id,p_content:content}),201)}
 if(['ship','complete'].includes(action)&&uuid(id||''))return ok(await rpc('lp_transition',{p_order:id,p_actor:user.id,p_action:action,p_tracking:body.tracking?text(body.tracking,2,200):null}));
 if(action==='withdraw'&&uuid(id||'')){const rows=await result(db.from('lp_listings').update({status:'withdrawn'}).eq('id',id).eq('seller_id',user.id).eq('status','available').eq('bid_count',0).select('id'));if(!rows.length)throw Error('Solo puedes retirar anuncios disponibles sin pujas.');return ok({success:true})}
 if(action==='report'&&uuid(targetId||'')){await result(db.from('lp_reports').insert({reporter_id:user.id,listing_id:targetId,reason:text(body.reason,10,2000)}));return ok({success:true})}
 if(action==='onboard'){if(simulated())return ok({error:'Estás en modo de prueba. No necesitas activar cobros reales.'},400);
  const st=stripe();const base=origin();let account=await result(db.from('lp_accounts').select('stripe_account_id').eq('user_id',user.id).maybeSingle());if(!account){const a=await st.accounts.create({type:'express',country:'ES',email:user.email,capabilities:{card_payments:{requested:true},transfers:{requested:true}},metadata:{user_id:user.id}},{idempotencyKey:'lapela-account-'+user.id});account={stripe_account_id:a.id};await result(db.from('lp_accounts').upsert({user_id:user.id,...account},{onConflict:'user_id'}))}const link=await st.accountLinks.create({account:account.stripe_account_id,refresh_url:base+'/user-profile',return_url:base+'/user-profile',type:'account_onboarding'});return ok({url:link.url});
 }
 return ok({error:'Ruta no encontrada'},404);
 }catch(e){const message=e instanceof Error?e.message:'No se ha podido completar la operación.';return ok({error:message},400)}}
