import {createClient} from '@supabase/supabase-js';
import {productSlug, extractIdFromSlug} from '@/lib/slugs';

export type PublicProfile={alias:string};

export function admin(){return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})}
export const publicFields='id,seller_id,title,description,category,condition,location,images,mode,price_cents,buy_now_cents,shipping_cents,delivery,ends_at,status,bid_count,created_at';
export function fallbackProfile(id:string):PublicProfile{return {alias:`usuario-${id.replace(/-/g,'').slice(0,12)}`}}
export function card(l:any,profile?:PublicProfile){const seller=profile||fallbackProfile(l.seller_id||l.id);return {id:l.id,slug:productSlug(l.id,l.title),name:l.title,description:l.description,price:l.price_cents/100,type:l.mode,image:l.images[0],detailImage:l.images[0],location:l.location,category:l.category,status:l.status,seller:seller.alias,sellerProfile:seller,buyer:null,bid_count:l.bid_count,auction_ends_at:l.ends_at,updated_at:l.created_at,time:l.created_at}}
export async function profilesById(db:any,ids:string[]){const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)return new Map<string,PublicProfile>();const {data,error}=await db.from('lp_profiles').select('id,alias').in('id',unique);if(error)throw Error('No se han podido cargar los perfiles.');const profiles=new Map<string,PublicProfile>((data||[]).map((p:any)=>[p.id,{alias:p.alias}]));for(const id of unique)if(!profiles.has(id))profiles.set(id,fallbackProfile(id));return profiles}
export async function rpc(name:string,args:Record<string,unknown>={}){const {data,error}=await admin().rpc(name,args);if(error)throw Error(error.message);return data}

export async function getListingByIdOrSlug(idOrSlug:string){const id=extractIdFromSlug(idOrSlug);if(!id)return null;const env=process.env.LAPELA_PAYMENTS_MODE==='simulated'?'sandbox':'live';const db=admin();const {data,error}=await db.from('lp_listings').select('*').eq('id',id).maybeSingle();if(error||!data||data.environment!==env)return null;const {data:bids,error:bidsError}=await db.from('lp_bids').select('id,bidder_id,amount_cents,created_at').eq('listing_id',id).order('created_at',{ascending:false}).limit(50);if(bidsError)return null;const profiles=await profilesById(db,[data.seller_id,...(bids||[]).map((b:any)=>b.bidder_id)]);const {seller_id,highest_bidder,...safe}=data;return {...safe,seller:profiles.get(seller_id),bids:(bids||[]).map(({bidder_id,...b}:any)=>({...b,bidder:profiles.get(bidder_id)})),slug:productSlug(data.id,data.title)}}

export async function getPublicProfile(alias:string){const db=admin();const normalized=alias.trim().toLowerCase();const {data:profile,error}=await db.from('lp_profiles').select('id,alias,show_purchases,created_at').eq('alias',normalized).maybeSingle();if(error||!profile)return null;const env=process.env.LAPELA_PAYMENTS_MODE==='simulated'?'sandbox':'live';const [activeResult,salesResult,reviewsResult,purchasesResult]=await Promise.all([db.from('lp_listings').select(publicFields).eq('seller_id',profile.id).eq('status','available').eq('environment',env).order('created_at',{ascending:false}).limit(24),db.from('lp_orders').select('id,listing:lp_listings!inner(environment)',{head:true,count:'exact'}).eq('seller_id',profile.id).eq('status','completed').eq('listing.environment',env),db.from('lp_reviews').select('id,author_id,score,comment,created_at,order:lp_orders!inner(id,listing:lp_listings!inner(environment))').eq('recipient_id',profile.id).eq('order.listing.environment',env).order('created_at',{ascending:false}).limit(30),profile.show_purchases?db.from('lp_orders').select('id,listing:lp_listings!inner(id,seller_id,title,description,category,location,images,mode,price_cents,ends_at,status,bid_count,created_at,environment)').eq('buyer_id',profile.id).eq('status','completed').eq('listing.environment',env).order('created_at',{ascending:false}).limit(24):Promise.resolve({data:[]})]);if(activeResult.error||salesResult.error||reviewsResult.error||(purchasesResult as any).error)throw Error('No se ha podido cargar el perfil.');const reviews=reviewsResult.data||[];const purchases=(purchasesResult as any).data||[];const ids=[...reviews.map((r:any)=>r.author_id),...purchases.map((o:any)=>o.listing?.seller_id).filter(Boolean),profile.id];const profiles=await profilesById(db,ids);const scoreCount=reviews.length;const averageScore=scoreCount?Math.round((reviews.reduce((sum:number,r:any)=>sum+r.score,0)/scoreCount)*10)/10:null;return {profile:{alias:profile.alias,memberSince:profile.created_at,showPurchases:profile.show_purchases},stats:{completedSales:salesResult.count||0,averageScore,reviewCount:scoreCount},activeListings:(activeResult.data||[]).map((l:any)=>card(l,profiles.get(profile.id))),purchases:profile.show_purchases?purchases.filter((o:any)=>o.listing).map((o:any)=>card(o.listing,profiles.get(o.listing.seller_id))):[],reviews:reviews.map((r:any)=>({id:r.id,score:r.score,comment:r.comment,created_at:r.created_at,author:profiles.get(r.author_id)}))}}
