'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useAuth} from '@/context/AuthContext';
import {supabase} from '@/utils/supabase';
import {api} from '@/lib/api';
export default function Account(){
 const {user,loading}=useAuth();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [profile,setProfile]=useState<any>(null);const [alias,setAlias]=useState('');const [showPurchases,setShowPurchases]=useState(false);
 useEffect(()=>{if(user)api('profile/me').then((p)=>{setProfile(p);setAlias(p.alias);setShowPurchases(p.show_purchases)}).catch((e)=>setError(e.message))},[user]);
 if(loading)return <p>Cargando cuenta…</p>;if(!user)return <div className="empty-state"><h1>Tu cuenta de La Pela</h1><Link href="/login" className="button primary">Entrar</Link></div>;
 async function saveProfile(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const p=await api('profile',{alias,showPurchases});setProfile(p);setAlias(p.alias);setShowPurchases(p.show_purchases)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="prose-page"><span className="eyebrow">MI CUENTA</span><h1>Todo listo para el próximo trato.</h1><p>{user.email}</p>
 <section className="account-section"><h2>Tu alias público</h2><p>Tu alias identifica tus anuncios, pujas y valoraciones. No muestra tu correo ni abre un canal de contacto.</p>{profile?<form onSubmit={saveProfile}><label>Alias<input className="field-input" value={alias} onChange={e=>setAlias(e.target.value.toLowerCase())} minLength={3} maxLength={30} pattern="[a-z0-9][a-z0-9_-]{2,29}" disabled={profile.alias_customized||busy} required/></label>{profile.alias_customized?<p className="muted">Tu alias está fijado. Contacta con soporte si necesitas cambiarlo.</p>:<p className="muted">Usa letras minúsculas, números, guiones o guiones bajos.</p>}<label className="check-row"><input type="checkbox" checked={showPurchases} onChange={e=>setShowPurchases(e.target.checked)} disabled={busy}/> Mostrar mis compras completadas en mi perfil público</label>{error&&<p className="error-message" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Guardando…':'Guardar perfil'}</button>{profile.alias&&<Link className="button" href={`/usuarios/${profile.alias}`}>Ver perfil público</Link>}</form>:<p>Cargando tu perfil…</p>}</section>
 <section className="account-section"><h2>Recibir pagos</h2><p>Completa tus datos en Stripe para activar los cobros de tus ventas. La Pela no almacena tus datos bancarios.</p><button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api('onboard',{});window.location.assign(r.url)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Preparando…':'Configurar cobros'}</button></section><section className="account-section"><h2>Compras, ventas y conversaciones</h2><Link className="button" href="/my-products">Ver mi actividad →</Link></section><button className="text-link" onClick={async()=>{await supabase.auth.signOut();window.location.assign('/')}}>Cerrar sesión</button></div>}
